# Generated by Django 3.1.5 on 2021-01-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=255, verbose_name='Long URL')),
                ('short_url', models.CharField(max_length=255, verbose_name='Short URL')),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': "Short URL's",
            },
        ),
    ]
