# Generated by Django 3.1.5 on 2021-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilantis', '0002_shorturl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='maximum_clicks',
            field=models.IntegerField(default=10, help_text='How many times link can be used before deactivation', verbose_name='Maximum number of clicks'),
        ),
    ]
