# Generated by Django 3.1.5 on 2021-01-30 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vilantis', '0003_auto_20210130_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clicked at')),
                ('ip', models.CharField(max_length=255, verbose_name='User IP')),
                ('referrer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referrer URL')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vilantis.shorturl', verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
