# Generated by Django 3.1.5 on 2021-01-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilantis', '0004_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expires at'),
        ),
    ]
